from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LOG_DIR = PROJECT_ROOT / "logs"
DEFAULT_SCREENSHOT_DIR = PROJECT_ROOT / "screenshots"
DEFAULT_TRACE_DIR = PROJECT_ROOT / "traces"

DEFAULT_VIEWPORT = {"width": 1366, "height": 768}
DEFAULT_NAVIGATION_TIMEOUT_MS = 30000
DEFAULT_ACTION_TIMEOUT_MS = 10000
MAX_DOM_TEXT_CHARS = 8000
MAX_CLICKABLE_ELEMENTS = 80
